# Generated by Django 2.0.5 on 2018-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('institution', models.CharField(max_length=60)),
                ('position', models.CharField(choices=[('C', 'Coordenador'), ('P', 'Pesquisador'), ('A', 'Aluno')], max_length=1)),
            ],
        ),
    ]
