# Generated by Django 2.0.5 on 2018-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lattes',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
