# Generated by Django 2.0.7 on 2018-10-10 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0004_auto_20181008_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.FileField(upload_to='imagens/', verbose_name='Documento')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.FileField(upload_to='imagens/', verbose_name='Documento')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image', models.FileField(upload_to='imagens/', verbose_name='Documento')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Texto em Inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='institution',
            field=models.CharField(max_length=60, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lattes',
            field=models.CharField(max_length=100, verbose_name='Link para o Lattes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(choices=[('C', 'Coordenador'), ('P', 'Pesquisador'), ('A', 'Aluno')], max_length=1, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_pt',
            field=models.TextField(verbose_name='Texto em Português'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo em Português'),
        ),
    ]
