# Generated by Django 2.0.6 on 2018-10-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0005_auto_20181010_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doi',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='doi',
            name='image',
        ),
        migrations.AddField(
            model_name='doi',
            name='ano',
            field=models.CharField(default='', max_length=4, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doi',
            name='authors',
            field=models.CharField(default='', max_length=200, verbose_name='Autores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doi',
            name='doi',
            field=models.CharField(default='', max_length=200, verbose_name='Doi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doi',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
