# Generated by Django 2.0.6 on 2018-10-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0006_auto_20181011_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='doi',
            name='authors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='doi',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Doi'),
        ),
        migrations.AlterField(
            model_name='doi',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='doi',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
