# Generated by Django 2.0.7 on 2018-10-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0008_auto_20181028_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destaques',
            name='created_date',
        ),
        migrations.AddField(
            model_name='destaques',
            name='text_en',
            field=models.TextField(default='', verbose_name='Texto em Inglês'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destaques',
            name='text_pt',
            field=models.TextField(default='', verbose_name='Texto em Português'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destaques',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Titulo em Inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destaques',
            name='image',
            field=models.FileField(upload_to='imagens/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='destaques',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo em Português'),
        ),
    ]
