# Generated by Django 2.0.7 on 2018-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0009_auto_20181028_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacoes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publicacoes',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='publicacoes',
            name='image',
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='authors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='publicacoes',
            name='position',
            field=models.CharField(choices=[('L', 'Livros'), ('C', 'Congressos'), ('O', 'Orientações')], default='', max_length=1, verbose_name='Tipo de Publicação'),
            preserve_default=False,
        ),
    ]
