# Generated by Django 2.1.2 on 2018-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0010_auto_20181028_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('L', 'O que é'), ('C', 'Objetivos'), ('O', 'Dados')], max_length=1, verbose_name='Tipo de Publicação')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo em Português')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titulo em Inglês')),
                ('text_pt', models.TextField(verbose_name='Texto em Português')),
                ('text_en', models.TextField(verbose_name='Texto em Inglês')),
            ],
        ),
    ]
