# Generated by Django 2.1.2 on 2018-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0012_auto_20181107_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('initials', models.CharField(max_length=8, verbose_name='Sigla')),
                ('contry', models.CharField(max_length=30, verbose_name='Pais')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
            ],
        ),
    ]
