# Generated by Django 2.1.2 on 2018-12-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0017_auto_20181128_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='csv'),
        ),
    ]
