# Generated by Django 2.0.6 on 2018-12-07 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0017_auto_20181128_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.FileField(blank=True, null=True, upload_to='dados/', verbose_name='Dados')),
                ('data_i', models.DateTimeField(blank=True, null=True, verbose_name='Data inicial')),
                ('data_f', models.DateTimeField(blank=True, null=True, verbose_name='Data final')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remo.Estacao', verbose_name='Estação')),
            ],
            options={
                'verbose_name': 'Estações',
                'verbose_name_plural': 'Estações',
            },
        ),
    ]
