# Generated by Django 2.0.6 on 2018-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0019_serie_prof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Campanhas', 'verbose_name_plural': 'Campanhas'},
        ),
        migrations.RemoveField(
            model_name='serie',
            name='dados',
        ),
        migrations.AddField(
            model_name='serie',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='csv'),
        ),
    ]
