# Generated by Django 2.1.2 on 2018-12-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0024_auto_20181209_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='date',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Data'),
        ),
    ]
