# Generated by Django 2.1.2 on 2018-12-10 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0025_auto_20181209_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data'),
        ),
    ]
