# Generated by Django 2.0.7 on 2018-12-12 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0027_auto_20181209_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remo.Institution', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='data_f',
            field=models.DateField(blank=True, null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='data_i',
            field=models.DateField(blank=True, null=True, verbose_name='Data inicial'),
        ),
    ]
