# Generated by Django 2.1.2 on 2018-12-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0018_estacao_csv'),
        ('remo', '0029_auto_20181212_0032'),
    ]

    operations = [
    ]
