# Generated by Django 2.1.2 on 2018-12-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0031_auto_20181220_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(choices=[('C', 'Coordenador'), ('P', 'Pesquisador'), ('A', 'Aluno'), ('T', 'Técnico')], max_length=1, verbose_name='Cargo'),
        ),
    ]
