# Generated by Django 2.1.2 on 2018-12-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0032_auto_20181220_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipe'},
        ),
    ]
