# Generated by Django 2.0.6 on 2018-12-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0034_auto_20181225_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doi',
            name='journal',
        ),
    ]
