# Generated by Django 2.0.6 on 2018-12-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0035_remove_doi_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categoria de Documento',
            },
        ),
        migrations.AddField(
            model_name='doc',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='remo.Index_Doc'),
            preserve_default=False,
        ),
    ]
