# Generated by Django 2.1.7 on 2019-03-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0037_destaque_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='author',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='Index_Doc',
        ),
    ]
