# Generated by Django 2.1.7 on 2019-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0039_auto_20190315_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='doi',
            field=models.CharField(blank=True, help_text='Caso a publicação não tenha DOI, preencher tudo manualmente', max_length=200, null=True, unique=True, verbose_name='DOI'),
        ),
    ]
