# Generated by Django 2.1.7 on 2019-03-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0040_auto_20190319_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='doi',
            field=models.CharField(blank=True, help_text='Ex: 10.1007/s10236-017-1113-9. Caso a publicação não tenha DOI, preencher os outros campos manualmente', max_length=200, null=True, unique=True, verbose_name='DOI'),
        ),
    ]
