# Generated by Django 2.1.7 on 2019-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0041_auto_20190320_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='contry',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(choices=[('A', 'Coordenador'), ('B', 'Pesquisador'), ('C', 'Aluno Pós-Graduação'), ('D', 'Aluno Graduação'), ('E', 'Técnico')], max_length=2, verbose_name='Cargo'),
        ),
    ]
