# Generated by Django 2.1.7 on 2019-04-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0043_auto_20190405_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='position',
            field=models.CharField(choices=[('A', 'Artigos'), ('B', 'Livros'), ('C', 'Congressos'), ('D', 'Orientações')], max_length=1, verbose_name='Tipo de Publicação'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo'),
        ),
    ]
