# Generated by Django 2.1.7 on 2019-04-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0044_auto_20190405_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='url',
        ),
    ]
