# Generated by Django 2.1.7 on 2019-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0045_remove_publicacao_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
