# Generated by Django 2.1.7 on 2019-04-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0046_publicacao_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='URL'),
        ),
    ]
