# Generated by Django 2.1.7 on 2019-04-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0048_auto_20190406_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instituições', 'verbose_name_plural': 'Instituições'},
        ),
    ]
