# Generated by Django 2.0.6 on 2019-05-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0050_auto_20190501_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
