# Generated by Django 2.0.6 on 2019-05-02 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0051_auto_20190501_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome do diretório')),
            ],
            options={
                'verbose_name': 'Diretórios',
                'verbose_name_plural': 'Diretórios',
            },
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='url',
        ),
        migrations.AddField(
            model_name='documentos',
            name='dire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='remo.Diretorios', verbose_name='Diretório'),
            preserve_default=False,
        ),
    ]
