# Generated by Django 2.1.7 on 2019-05-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0052_auto_20190502_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='infos',
        ),
    ]
