# Generated by Django 2.1.7 on 2019-05-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0053_remove_campanha_infos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='title',
            new_name='title_pt',
        ),
    ]
