# Generated by Django 2.1.7 on 2019-05-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0054_auto_20190504_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destaque',
            old_name='title',
            new_name='title_pt',
        ),
    ]
