# Generated by Django 2.1.7 on 2019-05-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0055_auto_20190504_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='dire',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='title',
            new_name='title_pt',
        ),
        migrations.DeleteModel(
            name='Diretorios',
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
