# Generated by Django 2.1.7 on 2019-05-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0056_auto_20190504_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome do diretório')),
            ],
            options={
                'verbose_name': 'Diretório',
                'verbose_name_plural': 'Diretórios',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo em Português')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titulo em Inglês')),
                ('docs', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Documento')),
                ('dire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remo.Diretorios', verbose_name='Diretório')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
