# Generated by Django 2.1.7 on 2019-05-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0057_diretorios_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='title_en',
        ),
    ]
