# Generated by Django 2.1.7 on 2019-06-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0058_remove_documentos_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(choices=[('A', 'Coordenador'), ('B', 'Pesquisador'), ('C', 'Aluno Pós-Graduação'), ('D', 'Aluno Graduação'), ('E', 'Técnico'), ('F', 'Pesquisador Egresso'), ('G', 'Colaborador Externo')], max_length=2, verbose_name='Cargo'),
        ),
    ]
