# Generated by Django 2.1.7 on 2019-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0059_auto_20190606_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lattes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Link para o Lattes'),
        ),
    ]
