# Generated by Django 2.0.5 on 2019-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0060_auto_20190609_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='title',
            field=models.CharField(blank=True, default='#', max_length=500, null=True, verbose_name='Titulo'),
        ),
    ]
