# Generated by Django 2.0.5 on 2019-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0061_auto_20190705_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('tel', models.CharField(max_length=30, verbose_name='Tel')),
            ],
            options={
                'verbose_name': 'Contatos',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='dire',
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='position',
            field=models.CharField(choices=[('A', 'Artigos'), ('B', 'Livros'), ('C', 'Congressos'), ('D', 'Monografia'), ('E', 'Mestrado'), ('F', 'Doutorado')], max_length=1, verbose_name='Tipo de Publicação'),
        ),
        migrations.DeleteModel(
            name='Diretorios',
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
