# Generated by Django 2.0.5 on 2019-07-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remo', '0062_auto_20190705_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contatos'},
        ),
    ]
